#include <vector>
#include <unordered_set>
#include <iostream>

#include "covering.h"
#include "utility.h"

using namespace std;

//this is a utility function, very helpful for me to confirm that all other covering methods do what they are supposed to do
void covering::print_covering(){
    cout << "Covering system with " << num_mod <<  " moduli from " << moduli[0] << " to " << moduli.back() << ", with LCM: "<< lcm << endl; 
    cout << "Moduli: ";
    for (int m : moduli){
        cout << m << ", "; 
    }
    cout << endl << "Residues: ";
    for (int r : residues){
        cout << r << ", ";
    }
    if (seed_code >= 0){
        cout << "Has seed: " << seed_code;
    }
    cout << endl;
}

//another utility function, helpful to make sure my connection struct is working as it is supposed to
void connection::print(){
    cout << "Connection from index " << index_out << " to " << index_in << ", from seed code " << code_out << " to " << code_in << " by prime " << prime << endl;
}

//this sets up the covering object
void covering::init(std::vector<int> ipt_moduli, std::vector<int> ipt_residues){
    moduli = ipt_moduli;
    residues = ipt_residues;
    num_mod = moduli.size(); 
    seed_code = -1; //this is initialized so as to make sure a covering indicates if it is part of a seed if and only if it is part of that seed
    lcm = vec_lcm(moduli);
}

//this method checks if a covering object actually reprsents a covering by its mathematical definition
//I use this method infrequently, as all covering operations I used are proved to be closed
//thus this method is mainly useful when copying over the moduli and residues of a proposed covering and declaring a object with it
bool covering::is_covering(){
    vector<bool> covered(lcm,0);
    for (int i = 0; i < num_mod; i++){
        for (int j = residues[i]; j < lcm; j+=moduli[i]){
            covered[j] = true;
        }
    }
    int count = 0;
    for (bool i : covered){
        count++; 
        if (!i){
            return false;
        }
    }
    return true;
}

//this checks that two covering objects are mathematical equal 
bool covering::equal(covering a){
    if (a.moduli.size() != moduli.size()) return false;
    if (a.moduli != moduli) return false;
    for(int i = num_mod-1; i >= 0; i--){ //by working from the highest moduli's residues firsts, I save a lot of computation, as these are least likely to be the same for two distinct coverings
        if (a.residues[i] != residues[i])return false; 
    }
    return true;
}

//this method returns a new covering that is mathematically equivelent to this covering times a prime
//in practice this can only generate a few new coverings, as only a few primes generate new coverings
//all other primes map to coverings already generated by these few primes
//the properties of this operation are what I am studying, and what my graph tries to investigate
covering covering::times(int p){
    covering ret;
    vector<int> new_residues;
    for (int i = 0; i < num_mod; i++){
        new_residues.push_back((residues[i]*p) % moduli[i]);
    }
    ret.init(moduli,new_residues);
    return ret;
}

//this method returns a new covering that is mathematically equivelent to this covering plus any integer 
//in practice, this can only generate least-common-multiple many new coverings due to properties of modular arithmetic
//doing this operation lcm many times generates what we call a "seed"
covering covering::plus(int m){
    covering ret;
    vector<int> new_residues;
    for (int i = 0; i < num_mod; i++){
        new_residues.push_back((residues[i]+m) % moduli[i]);
    }
    ret.init(moduli,new_residues);
    return ret;
}

//setters and getters

void covering::set_seed_code(int code){
    seed_code = code;
}

int covering::get_seed_code(){
    return seed_code;
}

long long covering::get_lcm(){
    return lcm;
}
